### PR TITLE
styling/header

### LINKED ISSUE #17: Hapus icon pesan
image

hapus aja icon ini @FaruqRahmadani

### PR DESCRIPTION
**Pull request by FaruqRahmadani**
Fixes #17

### CODE REVIEW

**Comment by FaruqRahmadani** [comment]
https://github.com/FaruqRahmadani/SI-Lembaga-Kursus-BPC/pull/21/commits/76f8aa577be2336b21c528108aa23aec06e0aab4
image

**Comment by dedyrosyadi** [comment]
@FaruqRahmadani proile, setting, help hapus aja ruq. pengaturan user ada menunya di sidebar lo ?

**Comment by FaruqRahmadani** [comment]
berarti ulun olah logout aja disitu lah ka @dedyrosyadi

**Comment by FaruqRahmadani** [comment]
image

**Pull request merged**
